### PR TITLE
Change mock to a test dependency

### PR DESCRIPTION
**Pull request by RoelandMatthijssens**

### CODE REVIEW

**Comment by ianonavy** [comment]
👍

**Comment by NicolasLM** [comment]
Also the feature in `setup.py` that tests for the existence of mock doesn't work properly. It still installs mock even if Python 3.5 has it in the standard library:

```
$ pip freeze
$ pip install imapclient
$ pip freeze
asn1crypto==0.22.0
backports.ssl==0.0.9
cffi==1.10.0
cryptography==1.8.1
idna==2.5
IMAPClient==1.0.2
mock==1.3.0
packaging==16.8
pbr==2.1.0
pycparser==2.17
pyOpenSSL==16.2.0
pyparsing==2.2.0
six==1.10.0
```

```
Python 3.5.2 (v3.5.2:4def2a2901a5, Jun 26 2016, 10:47:25) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
```

**Comment by Duologic** [comment]
@mjs Any chance this will get merged at some point?

**Comment by mjs** [comment]
Sorry for the delay. I'm travelling a lot at the moment and there hasn't been much time for IMAPClient.

I'm happy to merge this once I return home next week (I don't have a computer with me and want to merge this into multiple branches so want to hold off for now).

The reason for always installing mock by default was to allow the unit tests to be run for an installation but there's been enough push back on this that I'm happy to give up on that.

**Pull request merged**
